export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const SET_GENRE = 'SET_GENRE';
export const YEAR = 'YEAR';
export const SET_POPOVER_VALUE = 'SET_POPOVER_VALUE';
export const SORT_MOVIES_BY_POPULARITY = 'SORT_MOVIES_BY_POPULARITY';
